### ISSUE TITLE
Bug in Line no 7 of Java code

### ISSUE THREAD

**Issue by bipeensinha** [bipeensinha/SLAPPLEPROJECT#1]
There is bug in code @Suyog111  please fix it @PhaniPrakash helo suyoiu @AbdulBasith0 mentor the orogress 
![demo](https://user-images.githubusercontent.com/49720823/169660806-25b8aef0-28ea-4885-af68-35ef815aaefe.jpg)

**Comment by mobin-25-87** [comment]
Working on it

**Comment by Vishnuvardhan-Dudda** [comment]
I am not able to upload

**Comment by AbdulBasith0** [comment]
I'll make sure i mentor the progress properly.

**Comment by yssrun** [comment]
progress in ON

**Comment by bipeensinha** [comment]
Thank you issues cloded
